#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umount "${RCLONE_MOUNT_TARGET}"
mkdir -p "${RCLONE_MOUNT_TARGET}"
chown -R plex:plex "${RCLONE_MOUNT_TARGET}"
chown -R plex:plex "${RCLONE_MOUNT_CACHE_DIR}"
exec s6-setuidgid plex \
    rclone mount -v \
        --config="$RCLONE_CONFIG" \
        --cache-dir "${RCLONE_MOUNT_CACHE_DIR}" \
        --vfs-cache-mode full \
        "${RCLONE_MOUNT_DIR}" \
        "${RCLONE_MOUNT_TARGET}"
